/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package its.time.tracker

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        assertNotNull(App.appName, "DBS CLI App")
        assertNotNull(App.version, "0.0.1")
    }
}
